CREATE DATABASE LABORATORIO;
USE LABORATORIO;
DROP TABLE IF EXISTS FACTURAS;
CREATE TABLE FACTURAS(
    Letra CHAR,
    Numero INTEGER,
    ClienteID INTEGER,
    ArticuloID INTEGER,
    Fecha DATE,
    Monto DOUBLE,
    PRIMARY KEY(Letra,Numero)
);

DESC FACTURAS;

CREATE TABLE ARTICULOS(
    ArticuloID INT PRIMARY KEY,
    Nombre VARCHAR(50),
    PRECIO DOUBLE,
    Stock INT
);

DESC ARTICULOS;